fpga: dfl-cxl-cache: depend on DRM
This resolves an undefined reference to drm_clflush_virt_range()
when building a kernel without modules and minimal configuration.

Signed-off-by: Peter Colberg <peter.colberg@intel.com>